lassizon/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :products
  get "/products/search/", to: 'products#search'
  resources :payement_methods
  resources :reviews, only: [:index, :create]
  resources :purchases, only: [:index, :create, :show]
  resources :users, only: [:show, :destroy]

  root 'products#index'

  get "*path", to: 'application#catch_404', via: :all
  post "*path", to: 'application#catch_404', via: :all


end

lassizon/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :payement_methods, dependent: :destroy
  has_many :purchases, dependent: :destroy
  has_many :products, dependent: :destroy

  acts_as_user :roles => [ :user, :vendor, :admin ] #user 0, vendor 1, admin 2

  #support fro omniauth
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.name = auth.info.first_name
        user.surname = auth.info.last_name
        user.data = auth.info.birthday
        user.roles = :user
        user.roles_mask = 0
        user.save
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
        if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
            user.email = data["email"] if user.email.blank?
        end
    end
  end



  def how_many_sells
    if (self.roles_mask != 1)
        return
    end
    Product.where(user_id: self.id).count
  end

  def how_many_purchases
    if (self.roles_mask != 0)
        return
    end
    Purchase.where(user_id: self.id).count
  end

  def how_many_payementMethods
    if (self.roles_mask != 0)
        return
    end
    PayementMethod.where(user_id: self.id).count
  end

end

lassizon/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

    skip_before_action :verify_authenticity_token

    def facebook
        # You need to implement the method below in your model (e.g. app/models/user.rb)
        @user = User.from_omniauth(request.env["omniauth.auth"])

        if @user.persisted?
            sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
            set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
        else
            session["devise.facebook_data"] = request.env["omniauth.auth"]
            redirect_to new_user_registration_url
        end
    end

    def failure
        redirect_to root_path
    end
end

lassizon/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        if current_user && current_user.roles_mask == 2
            @users = User.where.not(id: current_user.id)
        else
            current_user
        end
    end

    def show
        id = params[:id]
        if id.nil? then
            redirect_to products_path
            return
        end
		@user = User.find(id)
    end

    def edit

    end

    def new

    end

    def update
        @user = current_user
        authorize! :update, @user, :message => "You fool! You cannot update user"
        @user.update_attributes!(params[:user].permit(:name, :surname, :data, :position))
        #flash[:notice] = "#{@user.name} was successfully updated."
        redirect_to user_path(@user)
    end

    def destroy
        id = params[:id]
        if id.nil? then
            redirect_to products_path
            return
        end
        @user = User.find(id)
        #authorize! :destroy, @user, :message => "You fool! You cannot destroy user"
        @user.destroy
        #flash[:notice] = "#{@user.name} has been deleted."
        if current_user && current_user.roles_mask == 2
            redirect_to user_path(current_user)
            return
        end
        redirect_to products_path
        return
    end

   def create
        @user = User.user!(params[:user].permit(:name, :surname, :data, :position))
        authorize! :create, @user, :message => "You fool! You cannot create user!"
        #flash[:notice] = "#{@user.name} was successfully created."
        redirect_to user_path(@user)
    end
end

lassizon/app/helpers/user_helper.rb
module UserHelper
end

lassizon/app/views/users/_user.html.haml
%head
    :css
        body{
            text-align:center;
        }

%body
%div
    = user.name
    = user.surname
    = user.email
    - if current_user && current_user.roles_mask == 2
        = button_to 'Delete', user_path(user), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'
    %br
%div

lassizon/app/views/users/index.html.haml
%ul.users
    = render @users

lassizon/app/views/users/show.html.haml
%head
    :css
        /* Always set the map height explicitly to define the size of the div
        * element that contains the map. */
        #map {
            height: 400px;
            width: 100%;
        }
        /* Optional: Makes the sample page fill the window. */
        html, body {
            height: 80%;
            margin: 0;
            padding: 0;
            text-align:center;
        }
        central{
            text-align:center;
        }
        list_of_users{
            text-align:center;
        }

%h1 Hi  #{current_user.name} !
%br
%div
    - if current_user && (current_user.roles_mask == 0)
        = link_to "Payment Methods", payement_methods_path, class: 'btn btn-primary', :id=>'central'
        %p You have registered #{current_user.how_many_payementMethods} payment methods
        = link_to "Purchases", purchases_path, class: 'btn btn-primary', :id=>'central'
        %p You have #{current_user.how_many_purchases} purchases
    - if current_user && current_user.roles_mask == 1
        %p{:id => "number_of_product"} You are selling #{current_user.how_many_sells} products
    %br
    %br
%div
%div
- if current_user && current_user.roles_mask != 2
    %p Click on this button to destroy your account
    = button_to 'Destroy', user_path(current_user), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'
    %br
%div
%div
    - if current_user && current_user.roles_mask == 2
        %h3{:id => "list_of_users"} Users registered over Lassizon
        %ul.users
            = render User.where.not(id: current_user.id)
%div
%br
%p Here you can see your position on Google Maps
%br
%div{:id=>"map"}
    :javascript
        var map, infoWindow;
        function initMap() {
        var pos = {lat: 41.9109, lng: 12.4818};
        map = new google.maps.Map(document.getElementById('map'), {
          center: pos,
          zoom: 6
        });
        //var marker = new google.maps.Marker({position: pos, map: map});
        infoWindow = new google.maps.InfoWindow;
        // HTML5 geolocation. Documentation on W3School
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var pos = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };
            var admin_pos = {
              lat: 41.445060,
              lng: 13.405450
            };
            var image = 'https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png';
            var marker = new google.maps.Marker({position: pos, map: map});
            var admin = new google.maps.Marker({position: admin_pos, map: map, icon:image });
            infoWindow.setPosition(pos);
            infoWindow.setContent("You're here");
            infoWindow.open(map);
            map.setCenter(pos);
          }, function() {
            handleLocationError(true, infoWindow, map.getCenter());
          });
        } else {
          // Browser doesn't support Geolocation
          handleLocationError(false, infoWindow, map.getCenter());
        }
        }

        function handleLocationError(browserHasGeolocation, infoWindow, pos) {
        infoWindow.setPosition(pos);
        infoWindow.setContent(browserHasGeolocation ?
                              'Error: The Geolocation service failed.' :
                              'Error: Your browser doesn\'t support geolocation.');
        infoWindow.open(map);
        }

%script{:async => "", :defer => "defer", :src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyCNaIbiOdXt26WJDmkhyItNXYeAIaZPbyc&callback=initMap"}